# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c113594a323b61463c521203640f09113bbabed5bed973389336ef2b224e4c949cf7ed15cf2f06a27cf67a750686fa3d1e6bb428058722649af98be5e7ef66c8

test:
  secret_key_base: dda2ea221ed28df7521af2256d6cff17d6798871b2f67d8dc86b7069cc5a61c0680c9a5d6c89e54f0ff2a63afbb1bd11a043ef2b0f69a157c57987c941fd2fdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
