# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b701d37b5f62dc176b27ffbd206efd1453b038a80a2cc4f12171dd91dc208a12430299f8ad43823232f5b85690d5c99614850c5298b417b9eaac72099fb19b45

test:
  secret_key_base: b739a13ca93397532c1959d14a07c84fdaed4774d59bf8138613937d967fc084508018fbd2b35534515936101434c5a83f294a1a186b03516c2e9a85462e725f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
